//! Browser-OAuth + polling login flow for the desktop app.
//!
//! Flow (production-tested pattern):
//!
//! 1. Desktop → POST /api/v1/auth/desktop/start
//!    Body: `{ device_fingerprint, device_name, os, state }`
//!    Reply: `{ flow_id, auth_url }`
//! 2. Desktop opens `auth_url` in the system browser.
//! 3. Browser → GET /auth/desktop/authorize?flow_id=…
//!    - Fast path: already logged in on web → complete + redirect /auth/desktop/done.
//!    - Slow path: redirect Google OAuth with state = flow.state.
//! 4. Google → GET /admin/oauth/callback?code=&state=
//!    - If state matches a pending login_flow → complete desktop flow → redirect /auth/desktop/done.
//!    - Else → web admin login (existing behavior).
//! 5. Desktop → GET /api/v1/auth/desktop/poll/:flow_id (every 2s).
//!    Reply: `{ status, access_token?, refresh_token?, user?, subscription? }`.
//!    On status=completed, server clears the token columns so the tokens are
//!    delivered exactly once.

use std::sync::Arc;

use askama::Template;
use axum::extract::{Json, Path, Query, State};
use axum::response::{Html, IntoResponse, Redirect, Response};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use tower_sessions::Session;

use crate::auth::{
    current_user_opt, encode_access_token, hash_token, random_token, tier_for,
    REFRESH_TOKEN_TTL_SECS,
};
use crate::error::{AppError, AppResult};
use crate::models::User;
use crate::state::AppState;

/// Login-flow rows live this long. The desktop polls every 2 seconds, so 8
/// minutes gives users time to fumble with passwords / 2FA without making
/// expired rows accumulate forever.
const FLOW_TTL_SECS: i64 = 8 * 60;

// ---------- 1. /api/v1/auth/desktop/start ----------

#[derive(Deserialize)]
pub struct StartReq {
    pub device_fingerprint: String,
    pub device_name: String,
    pub os: String,
    /// CSRF state token generated by the desktop app. Used as the OAuth
    /// state too, so the callback handler can find the matching flow.
    pub state: String,
}

#[derive(Serialize)]
pub struct StartResp {
    pub flow_id: String,
    pub auth_url: String,
}

pub async fn start(
    State(state): State<Arc<AppState>>,
    Json(body): Json<StartReq>,
) -> AppResult<Json<StartResp>> {
    if !(8..=256).contains(&body.device_fingerprint.len()) {
        return Err(AppError::BadRequest("device_fingerprint length".into()));
    }
    if !(16..=256).contains(&body.state.len()) {
        return Err(AppError::BadRequest("state length".into()));
    }
    if body.device_name.is_empty() || body.device_name.len() > 256 {
        return Err(AppError::BadRequest("device_name length".into()));
    }
    if body.os.is_empty() || body.os.len() > 64 {
        return Err(AppError::BadRequest("os length".into()));
    }

    let flow_id = uuid::Uuid::new_v4().to_string();
    let now = chrono::Utc::now().timestamp();
    let expires_at = now + FLOW_TTL_SECS;

    sqlx::query(
        "INSERT INTO login_flows
           (id, state, device_fingerprint, device_name, device_os, status, expires_at, created_at)
         VALUES (?, ?, ?, ?, ?, 'pending', ?, ?)",
    )
    .bind(&flow_id)
    .bind(&body.state)
    .bind(&body.device_fingerprint)
    .bind(&body.device_name)
    .bind(&body.os)
    .bind(expires_at)
    .bind(now)
    .execute(&state.db)
    .await
    .map_err(|e| match &e {
        sqlx::Error::Database(db) if db.is_unique_violation() => {
            AppError::BadRequest("state already used".into())
        }
        _ => AppError::Internal(e.to_string()),
    })?;

    // The auth_url goes to our own server, not Google directly — that way
    // we can swap providers (or take the fast-path web-session route)
    // without the desktop app caring.
    let auth_url = format!(
        "{}/auth/desktop/authorize?flow_id={}",
        state.config.public_url.trim_end_matches('/'),
        flow_id
    );

    Ok(Json(StartResp { flow_id, auth_url }))
}

// ---------- 2. /auth/desktop/authorize ----------

#[derive(Deserialize)]
pub struct AuthorizeQuery {
    flow_id: String,
}

pub async fn authorize(
    State(state): State<Arc<AppState>>,
    session: Session,
    Query(q): Query<AuthorizeQuery>,
) -> AppResult<Response> {
    let row: Option<(String, String, i64)> =
        sqlx::query_as("SELECT state, status, expires_at FROM login_flows WHERE id = ?")
            .bind(&q.flow_id)
            .fetch_optional(&state.db)
            .await?;

    let Some((flow_state, status, expires_at)) = row else {
        return Err(AppError::NotFound);
    };
    if status != "pending" {
        // Already done — show the done page so the user isn't confused.
        return Ok(Redirect::to("/auth/desktop/done").into_response());
    }
    if chrono::Utc::now().timestamp() > expires_at {
        let _ = sqlx::query("UPDATE login_flows SET status = 'expired' WHERE id = ?")
            .bind(&q.flow_id)
            .execute(&state.db)
            .await;
        return Err(AppError::BadRequest("flow expired".into()));
    }

    // Fast path: already authenticated as a web user.
    if let Some(user) = current_user_opt(&state, &session).await {
        let outcome = complete_desktop_flow_if_match(&state, &flow_state, &user).await?;
        if outcome.matched {
            return Ok(Redirect::to("/auth/desktop/done").into_response());
        }
    }

    // Slow path: hand off to Google with our flow's `state`.
    let redirect_uri = format!(
        "{}/admin/oauth/callback",
        state.config.public_url.trim_end_matches('/')
    );
    let url = format!(
        "https://accounts.google.com/o/oauth2/v2/auth?\
         client_id={cid}&redirect_uri={ru}&response_type=code&\
         scope=openid%20email%20profile&state={st}&\
         access_type=online&prompt=select_account",
        cid = url::form_urlencoded::byte_serialize(state.config.google_client_id.as_bytes())
            .collect::<String>(),
        ru = url::form_urlencoded::byte_serialize(redirect_uri.as_bytes()).collect::<String>(),
        st = url::form_urlencoded::byte_serialize(flow_state.as_bytes()).collect::<String>(),
    );
    Ok(Redirect::to(&url).into_response())
}

// ---------- 4. /api/v1/auth/desktop/poll/:flow_id ----------

pub async fn poll(
    State(state): State<Arc<AppState>>,
    Path(flow_id): Path<String>,
) -> AppResult<Json<Value>> {
    // Sweep expired flows before answering. Cheap because the index makes
    // this O(log n) per expired row.
    let now = chrono::Utc::now().timestamp();
    let _ = sqlx::query(
        "UPDATE login_flows SET status = 'expired'
           WHERE status = 'pending' AND expires_at < ?",
    )
    .bind(now)
    .execute(&state.db)
    .await?;

    // (status, access_token, refresh_token, user_id) — clippy::type_complexity
    type PollRow = (String, Option<String>, Option<String>, Option<String>);
    let row: Option<PollRow> = sqlx::query_as(
        "SELECT status, access_token, refresh_token, user_id
           FROM login_flows WHERE id = ?",
    )
    .bind(&flow_id)
    .fetch_optional(&state.db)
    .await?;

    let Some((status, access_token, refresh_token, user_id)) = row else {
        return Err(AppError::NotFound);
    };

    let _ = sqlx::query("UPDATE login_flows SET polled_at = ? WHERE id = ?")
        .bind(now)
        .bind(&flow_id)
        .execute(&state.db)
        .await;

    match status.as_str() {
        "pending" => Ok(Json(json!({ "status": "pending" }))),
        "expired" => Ok(Json(json!({ "status": "expired" }))),
        "device_limit_exceeded" => Ok(Json(json!({ "status": "device_limit_exceeded" }))),
        "not_member" => Ok(Json(json!({ "status": "not_member" }))),
        "completed" => {
            let (Some(access_token), Some(refresh_token), Some(uid)) =
                (access_token, refresh_token, user_id)
            else {
                // Tokens already consumed by an earlier poll — treat as
                // unknown so the client doesn't get a partial payload.
                return Err(AppError::NotFound);
            };

            // One-shot delivery: clear tokens so a subsequent poll (or a
            // database leak) can't replay them.
            sqlx::query(
                "UPDATE login_flows SET access_token = NULL, refresh_token = NULL WHERE id = ?",
            )
            .bind(&flow_id)
            .execute(&state.db)
            .await?;

            let user = sqlx::query_as::<_, User>("SELECT * FROM users WHERE id = ?")
                .bind(&uid)
                .fetch_one(&state.db)
                .await?;

            Ok(Json(json!({
                "status": "completed",
                "access_token": access_token,
                "refresh_token": refresh_token,
                "user": {
                    "id": user.id,
                    "email": user.email,
                    "name": user.name,
                    "picture": user.picture,
                },
                "subscription": {
                    "tier": tier_for(&user),
                },
            })))
        }
        other => Ok(Json(json!({ "status": other }))),
    }
}

// ---------- 5. /auth/desktop/done ----------

#[derive(Template)]
#[template(path = "desktop_done.html")]
pub struct DesktopDoneTemplate;

pub async fn done() -> Html<String> {
    Html(DesktopDoneTemplate.render().unwrap())
}

// ---------- Core: complete_desktop_flow_if_match ----------

pub struct CompletionOutcome {
    pub matched: bool,
}

/// Finish an in-flight desktop login: validates the user, enforces the
/// device limit, upserts the device row, mints tokens, and stashes them on
/// the flow row for the next poll. Returns `matched=true` when a pending
/// flow was found (even if it ended in an error status).
pub async fn complete_desktop_flow_if_match(
    state: &AppState,
    oauth_state: &str,
    user: &User,
) -> Result<CompletionOutcome, AppError> {
    let flow: Option<(String, String, String, String, i64)> = sqlx::query_as(
        "SELECT id, device_fingerprint, device_name, device_os, expires_at
           FROM login_flows WHERE state = ? AND status = 'pending'",
    )
    .bind(oauth_state)
    .fetch_optional(&state.db)
    .await?;

    let Some((flow_id, fingerprint, device_name, device_os, expires_at)) = flow else {
        return Ok(CompletionOutcome { matched: false });
    };

    let now = chrono::Utc::now().timestamp();
    if now > expires_at {
        sqlx::query("UPDATE login_flows SET status = 'expired' WHERE id = ?")
            .bind(&flow_id)
            .execute(&state.db)
            .await?;
        return Ok(CompletionOutcome { matched: true });
    }

    // Membership gate. Non-members cannot pair a device at all.
    if !user.is_member_bool() {
        sqlx::query("UPDATE login_flows SET status = 'not_member', user_id = ? WHERE id = ?")
            .bind(&user.id)
            .bind(&flow_id)
            .execute(&state.db)
            .await?;
        return Ok(CompletionOutcome { matched: true });
    }

    // Device limit. Re-pairing the same fingerprint never counts against
    // the limit; it just refreshes the existing row.
    let tier = tier_for(user);
    let limit = state.config.desktop_device_limit;
    if tier != "admin" && limit > 0 {
        let active: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM devices
               WHERE user_id = ? AND revoked_at IS NULL AND fingerprint != ?",
        )
        .bind(&user.id)
        .bind(&fingerprint)
        .fetch_one(&state.db)
        .await?;
        if active as u32 >= limit {
            sqlx::query(
                "UPDATE login_flows SET status = 'device_limit_exceeded', user_id = ?
                   WHERE id = ?",
            )
            .bind(&user.id)
            .bind(&flow_id)
            .execute(&state.db)
            .await?;
            return Ok(CompletionOutcome { matched: true });
        }
    }

    // Upsert device row. ON CONFLICT keeps the existing id so the desktop
    // app's last-known device_id keeps working across re-pairings.
    let new_device_id = uuid::Uuid::new_v4().to_string();
    sqlx::query(
        "INSERT INTO devices (id, user_id, fingerprint, name, os, created_at, last_seen_at, revoked_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, NULL)
         ON CONFLICT(user_id, fingerprint) DO UPDATE SET
            name = excluded.name,
            os = excluded.os,
            last_seen_at = excluded.last_seen_at,
            revoked_at = NULL",
    )
    .bind(&new_device_id)
    .bind(&user.id)
    .bind(&fingerprint)
    .bind(&device_name)
    .bind(&device_os)
    .bind(now)
    .bind(now)
    .execute(&state.db)
    .await?;

    let device_id: String =
        sqlx::query_scalar("SELECT id FROM devices WHERE user_id = ? AND fingerprint = ?")
            .bind(&user.id)
            .bind(&fingerprint)
            .fetch_one(&state.db)
            .await?;

    // Mint a fresh refresh-session row. The plaintext refresh token is
    // stashed on the flow row for one-shot delivery; only its hash lives in
    // auth_sessions long-term.
    let refresh_token = random_token();
    let refresh_hash = hash_token(&refresh_token);
    let session_id = uuid::Uuid::new_v4().to_string();
    sqlx::query(
        "INSERT INTO auth_sessions
           (id, user_id, device_id, refresh_token_hash, issued_at, expires_at)
         VALUES (?, ?, ?, ?, ?, ?)",
    )
    .bind(&session_id)
    .bind(&user.id)
    .bind(&device_id)
    .bind(&refresh_hash)
    .bind(now)
    .bind(now + REFRESH_TOKEN_TTL_SECS)
    .execute(&state.db)
    .await?;

    let (access_token, _exp) = encode_access_token(state, &user.id, &device_id, tier)?;

    sqlx::query(
        "UPDATE login_flows SET
           status = 'completed',
           user_id = ?,
           device_id = ?,
           auth_session_id = ?,
           refresh_token = ?,
           access_token = ?,
           completed_at = ?
         WHERE id = ?",
    )
    .bind(&user.id)
    .bind(&device_id)
    .bind(&session_id)
    .bind(&refresh_token)
    .bind(&access_token)
    .bind(now)
    .bind(&flow_id)
    .execute(&state.db)
    .await?;

    Ok(CompletionOutcome { matched: true })
}
